torrentmax: fix 2e5ef30
use of the escape quote causes :has() to not match, generating
System.Exception: Error while parsing field=category, selector=div.media-heading a, value=humor: Object reference not set to an instance of an object.

also 19 is not a category as far as I can tell

added infohash so we can drop hardcoded tracker list on download block